[project]
name = "ghqc"
r_version = "4.5"

# A list of repositories to fetch packages from. Order matters: we will try to get a package from each repository in order.
# The alias is only used in this file if you want to specifically require a dependency to come from a certain repository.
# Example: { alias = "PPM", url = "https://packagemanager.posit.co/cran/latest" },
repositories = [
    {alias = "PRISM", url = "https://prism.dev.a2-ai.cloud/rpkgs/stratus/2026-02-13"},
]

# A list of packages to install and any additional configuration
# Examples:
    # "dplyr",
    # {name = "dplyr", repository = "CRAN"},
    # {name = "dplyr", git = "https://github.com/tidyverse/dplyr.git", tag = "v1.1.4"},
dependencies = [
    "rextendr",
    "devtools",
    #{ name = "ghqc", path = ".", dependencies_only = false, install_suggestions = true },
    { name = "ghqc", git = "https://github.com/a2-ai/ghqctoolkit", directory = "R/ghqc", branch = "r_pkg" },
]
